export const ROUTES = {
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  PROFILE: '/profile',
  APPEARANCE: '/appearance',
  PROJECTS: '/projects',
  PROJECT: '/projects/:projectId',
  PROJECT_EDIT: '/projects/:projectId/edit',
  PROJECT_CREATE: '/projects/add',
  PROJECT_TASKS: '/projects/:projectId/tasks',
  PROJECT_TASK_CREATE: '/projects/:projectId/tasks/add',
  PROJECT_TASK: '/projects/:projectId/tasks/:taskId',
  PROJECT_TASK_EDIT: '/projects/:projectId/tasks/:taskId/edit',
  USERS: '/users',
  USERS_LIST: '/users/list',
};
